### PR TITLE
Ensure that the test runner can be called from any wording dir

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by jcalderonzumba** [comment]
LGTM 👍 
Maybe you could help me figure out why this particular job in the test matrix is making a really big crash
https://travis-ci.org/jcalderonzumba/MinkPhantomJSDriver/jobs/186017542

It seems like something has happened in guzzle because using 
`"env": "COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak" 
`
now throws lots of warnings.

**Comment by stof** [comment]
@jcalderonzumba this looks related to an issue in the new release of guzzle. It does not seem related to my change. Maybe they have a wrong lower bound somewhere

**Comment by jcalderonzumba** [comment]
Yes, is not  your change, i have seen error this in previous commits i have pushed but haven't managed to find the root cause to fix it.

**Comment by jcalderonzumba** [comment]
I think it might have to do with this: https://github.com/jcalderonzumba/gastonjs/pull/15/ where we support guzzle 5 or 6.

**Pull request merged**
