### PR TITLE
Use the official driver testsuite

### PR DESCRIPTION
**Pull request by stof**
Thanks to recent changes in the official driver testsuite to ensure that valid HTML is output when dumping things (not yet merged, see https://github.com/minkphp/driver-testsuite/pull/7), it will now be possible to stop altering tests, making the testsuite much easier to maintain (your copied testcases were outdated, missing some tests)

The JS evaluation and execution is also fixed to support all necessary syntaxes (FYI, the fix being done is directly copied from ZombieDriver, as the syntaxes supported natively are the same than in ZombieDriver)

There are a few remaining failures:
- a basic auth tests (which was already skipped previously, and so is kept skipped for now)
- an HTML5 form tests (which I'm skipping for now), where the ``color`` input is not supported
- a test relying on ``setValue`` for a file input (not implemented in your driver), which cannot be skipped for now (the test uses a data provider, and your skipping system does not support skipping a single provided test) so it fails for now
- a test failing when asserting the dump for a field value containing quotes. We have the same failure in Selenium2Driver, and I haven't debugged it yet, so this should wait
- the status code test for 404 is failing, but this is an issue in the driver testsuite itself (I forgot this page when fixing the issues with HTML pages not being valid HTML)

### CODE REVIEW

**Comment by jcalderonzumba** [comment]
@stof Thanks for the changes, i'll wait for the merge of https://github.com/minkphp/driver-testsuite/pull/7 and then I will address the failures you are commenting.
BTW, when could we consider putting this driver in the Mink documentation? I would love people seeing the drive in your doc, that will give it more visibility

**Comment by stof** [comment]
@jcalderonzumba once it uses the unmodified testsuite, this is indeed totally possible (creating a new section ``Third-party drivers`` or something like that)

**Comment by jcalderonzumba** [comment]
@stof I have force to run the tests again and now things look better however there's still one failure in this test:
Behat\Mink\Tests\Driver\Form\GeneralTest::testAdvancedForm that i think is related to how we check for things after dumping stuff. I'm merging this change.

**Comment by stof** [comment]
The failure in ``testAdvancedForm`` is the failure we also have for Selenium2Driver. We haven't it debugged yet (older versions of Selenium/Firefox were not failing it btw).
Once we fix it for Selenium2, it might fix it for you as well.

the failure in ``testHtml5FormRadioAttribute`` should be debugged in your driver though

**Comment by jcalderonzumba** [comment]
Yes the other failure is something i have to fix 👍

**Pull request merged**
